package net.diverginglensestudios.undeadmod.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class ModAnimationDefinitions {

//////////////////////////////////////////////////
/////////////UNDEAD_ARCHEOLOGIST//////////////////
//////////////////////////////////////////////////

public static final AnimationDefinition UNDEAD_ARCHEOLOGIST_WALK = AnimationDefinition.Builder.withLength(2f).looping()
.addAnimation("right_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("right_leg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_leg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("body",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR))).build();

public static final AnimationDefinition UNDEAD_ARCHEOLOGIST_IDLE = AnimationDefinition.Builder.withLength(4f).looping()
.addAnimation("right_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(3f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(3f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR))).build();

public static final AnimationDefinition UNDEAD_ARCHEOLOGIST_ATTACK = AnimationDefinition.Builder.withLength(0.5f)
.addAnimation("right_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR))).build();

//////////////////////////////////////////////////
/////////////FOSSILIZED_ZOMBIE////////////////////
//////////////////////////////////////////////////

public static final AnimationDefinition FOSSILIZED_ZOMBIE_WALK = AnimationDefinition.Builder.withLength(1.5f).looping()
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, -4f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, 0f, -4f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("torso",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-98f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(-95f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("right_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-95f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(-98f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_leg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0.6f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0.6f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_leg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("right_leg",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0.6f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0.6f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("right_leg",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.125f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR))).build();

public static final AnimationDefinition FOSSILIZED_ZOMBIE_IDLE = AnimationDefinition.Builder.withLength(3f).looping()
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(9.96f, 0.87f, -4.92f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("torso",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(2.95833f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-1f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(3f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("right_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-1f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(3f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR))).build();
public static final AnimationDefinition ATTACK = AnimationDefinition.Builder.withLength(0.70833f)
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-2.5f, 0f, -5f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.70833f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("torso",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.70833f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("left_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(-110f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.70833f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("right_arm",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(-110f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.70833f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR))).build();
}
